language: perl

sudo: false

os:
  - linux
  - osx

osx_image: xcode7.3

env:
  - ALIEN_INSTALL_TYPE=share
  - ALIEN_INSTALL_TYPE=default
  - ALIEN_INSTALL_TYPE=system

matrix:
  exclude:
    - os: osx
      perl: "5.14"

perl:
  - "5.14"
  - "5.26"

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      eval "$($HOME/perl5/perlbrew/bin/perlbrew env $TRAVIS_PERL_VERSION)"
      export PATH=${PERLBREW_PATH:-$PERLBREW_ROOT/bin}:$PATH
      perlbrew --quiet install-cpanm --force
      cpanm --version
      env | grep -i ^perl
      export SSL_DIR=/usr/local/Cellar/openssl/1.0.2j
    fi
  - |
    if [[ "$ALIEN_INSTALL_TYPE" == "system" ]]; then
      curl -Lo $HOME/libdeflate.tar.gz https://github.com/ebiggers/libdeflate/archive/v1.0.tar.gz
      tar -C $HOME -zxf $HOME/libdeflate.tar.gz
      make -C $HOME/libdeflate-1.0 libdeflate.a gzip gunzip checksum CFLAGS=-fPIC
      export ALIEN_LIBDEFLATE_PROBE_CFLAGS=-I$HOME/libdeflate-1.0
      export ALIEN_LIBDEFLATE_PROBE_LDFLAGS=-L$HOME/libdeflate-1.0
    fi

install:
  - cpanm --with-develop --installdeps -n -q .
